config/routes.rb
Rails.application.routes.draw do
  resources :gossips
  devise_for :moussaillons
  get 'home/index'

  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gossip.rb
class Gossip < ApplicationRecord



belongs_to :moussaillon, :optional => true
	
end

app/models/moussaillon.rb
class Moussaillon < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

	

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :gossips

  validate :validate_invite, :on => :create
  attr_accessor :invite

  def validate_invite
    if self.invite != "GOSSIP_2017"
      self.errors[:base] << "The Invitation Code is Incorrect"
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


	protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :invite) }
  end


end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :set_gossip, only: [:show, :edit, :update, :destroy]

  # GET /gossips
  # GET /gossips.json
  def index
    @gossips = Gossip.all
  end

  # GET /gossips/1
  # GET /gossips/1.json
  def show
  end

  # GET /gossips/new
  def new
    @gossip = Gossip.new
  end

  # GET /gossips/1/edit
  def edit
  end

  # POST /gossips
  # POST /gossips.json
  def create
    @gossip = Gossip.new(gossip_params)

    respond_to do |format|
      if @gossip.save
        format.html { redirect_to @gossip, notice: 'Gossip was successfully created.' }
        format.json { render :show, status: :created, location: @gossip }
      else
        format.html { render :new }
        format.json { render json: @gossip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gossips/1
  # PATCH/PUT /gossips/1.json
  def update
    respond_to do |format|
      if @gossip.update(gossip_params)
        format.html { redirect_to @gossip, notice: 'Gossip was successfully updated.' }
        format.json { render :show, status: :ok, location: @gossip }
      else
        format.html { render :edit }
        format.json { render json: @gossip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gossips/1
  # DELETE /gossips/1.json
  def destroy
    @gossip.destroy
    respond_to do |format|
      format.html { redirect_to gossips_url, notice: 'Gossip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gossip
      @gossip = Gossip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gossip_params
      params.require(:gossip).permit(:content)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   def index
    @gossips = Gossip.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/gossips/_form.html.erb
<%= form_with(model: gossip, local: true) do |form| %>
  <% if gossip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gossip.errors.count, "error") %> prohibited this gossip from being saved:</h2>

      <ul>
      <% gossip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :gossip_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gossips/edit.html.erb
<h1>Editing Gossip</h1>

<%= render 'form', gossip: @gossip %>

<%= link_to 'Show', @gossip %> |
<%= link_to 'Back', gossips_path %>

app/views/gossips/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gossips</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gossips.each do |gossip| %>
      <tr>
        <td><%= gossip.content %></td>
        <td><%= link_to 'Show', gossip %></td>
        <td><%= link_to 'Edit', edit_gossip_path(gossip) %></td>
        <td><%= link_to 'Destroy', gossip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gossip', new_gossip_path %>

app/views/gossips/new.html.erb
<h1>New Gossip</h1>

<%= render 'form', gossip: @gossip %>

<%= link_to 'Back', gossips_path %>

app/views/gossips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @gossip.content %>
</p>

<%= link_to 'Edit', edit_gossip_path(@gossip) %> |
<%= link_to 'Back', gossips_path %>

app/views/home/index.html.erb
<ul> 
	<% if moussaillon_signed_in? %> 

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gossips.each do |gossip| %>
      <tr>
        <td><%= gossip.content %></td>
        <td><%= link_to 'Show', gossip %></td>
        <td><%= link_to 'Edit', edit_gossip_path(gossip) %></td>
        <td><%= link_to 'Destroy', gossip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gossip', new_gossip_path %>


	<li>
		<%= link_to "Sign Out", destroy_moussaillon_session_path, method: :delete %>
	</li>

	<li>
		<%= link_to "Créer un gossip" %>
	</li>

	<% else %>
	
		<img src=http://www.psychsearch.net/wp-content/uploads/warning.gif>

<p>Tu n'es pas connecté il faut d'abord que tu te connectes ou t'inscrives !</p>

	<li>
		<%= link_to "Sign in", new_moussaillon_session_path %>
	</li>


	<li>
		<%= link_to "Sign up", new_moussaillon_registration_path %>
	</li>

	<% end %> 

</ul> 

<!--


-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gossips encore !</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


#### HEADER #######

<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to 'Devise Demo', root_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if moussaillon_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= current_moussaillon.email %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Profile', edit_moussaillon_registration_path %></li>
              <li><%= link_to 'Log out', destroy_moussaillon_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log In', new_moussaillon_session_path %></li>
          <li><%= link_to 'Sign Up', new_moussaillon_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

#### HEADER ####
  </head>

  <body>

<%= yield %>

  </body>
</html>